# Generated by Django 6.0.5 on 2026-06-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_profile_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizerprofile',
            old_name='company_name',
            new_name='company',
        ),
    ]
