# Generated by Django 6.0.5 on 2026-06-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_company_name_organizerprofile_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='organizerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizerprofile',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
