# Generated by Django 6.0.5 on 2026-06-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_organizerprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimage',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='service',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
