# Generated by Django 6.1.1 on 2026-10-01 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_booking_postlike_savedpost_viewhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='packages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='price_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='organizers/profiles/'),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='availability',
            field=models.CharField(blank=True, default='Available', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='event_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='locality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='service',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='organizers/portfolio/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='api.portfolioimage')),
            ],
        ),
    ]
